services:
  api-gateway:
    image: ${DOCKERHUB_USERNAME}/api-gateway:latest
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - microservices-net

  user-service:
    image: ${DOCKERHUB_USERNAME}/user-service:latest
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
    restart: always
    environment:
      - USER_DATABASE_URL=${USER_DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - microservices-net

  auth-service:
    image: ${DOCKERHUB_USERNAME}/auth-service:latest
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    restart: always
    environment:
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - SENDGRID_CONFIRM_ACCOUNT_TEMPLATE_ID=${SENDGRID_CONFIRM_ACCOUNT_TEMPLATE_ID}
      - SENDGRID_RESET_PASSWORD_TEMPLATE_ID=${SENDGRID_RESET_PASSWORD_TEMPLATE_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_IOS_CLIENT_ID=${GOOGLE_IOS_CLIENT_ID}
      - GOOGLE_ANDROID_CLIENT_ID=${GOOGLE_ANDROID_CLIENT_ID}
    networks:
      - microservices-net

  media-service:
    image: ${DOCKERHUB_USERNAME}/media-service:latest
    build:
      context: .
      dockerfile: ./apps/media-service/Dockerfile
    restart: always
    environment:
      - MEDIA_DATABASE_URL=${MEDIA_DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    networks:
      - microservices-net

  payment-service:
    image: ${DOCKERHUB_USERNAME}/payment-service:latest
    build:
      context: .
      dockerfile: ./apps/payment-service/Dockerfile
    restart: always
    ports:
      - '3006:3000'
    environment:
      - PAYMENT_DATABASE_URL=${PAYMENT_DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    networks:
      - microservices-net

  mail-service:
    image: ${DOCKERHUB_USERNAME}/mail-service:latest
    build:
      context: .
      dockerfile: ./apps/mail-service/Dockerfile
    restart: always
    environment:
      - WEBHOOK_PORT=3006
      - RABBITMQ_URL=${RABBITMQ_URL}
      - MAIL_QUEUE_HOST=${MAIL_QUEUE_HOST}
      - MAIL_QUEUE_PORT=${MAIL_QUEUE_PORT}
      - MAIL_QUEUE_PASSWORD=${MAIL_QUEUE_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
    networks:
      - microservices-net

  conversation-service:
    image: ${DOCKERHUB_USERNAME}/conversation-service:latest
    build:
      context: .
      dockerfile: ./apps/conversation-service/Dockerfile
    restart: always
    ports:
      - '3005:3005'
    environment:
      - CONVERSATION_PORT=${CONVERSATION_PORT}
      - CONVERSATION_DATABASE_URL=${CONVERSATION_DATABASE_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
