import { TranscriptSegment } from '@common/ai/interfaces/transcription-result.interface';
import { ReelVisibility } from '@common/content/schemas/reel-visibility.schema';
import type { RecommendationMetadata } from '@common/recommendation/interfaces/recommendation-metadata.interface';

export class Reel {
  id: string;
  userId: string;
  mediaKey: string;
  title?: string;
  description?: string;
  tags: string[];
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';
  visibility: ReelVisibility;
  viewCount: bigint;
  transcript?: string;
  transcriptVtt?: string;
  transcriptSegments?: TranscriptSegment[];
  thumbnailKey?: string;
  processingStage?: string;
  processingMessage?: string;
  processingProgress?: number;
  processingAttemptId?: string;
  processingStartedAt?: Date;
  processingFailedAt?: Date;
  processingCompletedAt?: Date;
  processingErrorCode?: string;
  processingErrorDetail?: string;
  sourceDurationMs?: number;
  sourceWidth?: number;
  sourceHeight?: number;
  sourceFps?: number;
  sourceBitrateKbps?: number;
  sourceHasAudio?: boolean;
  sourceRotation?: number;
  encodedVariantCount?: number;
  encodedMaxHeight?: number;
  encodedFps?: number;
  createdAt: Date;
  updatedAt: Date;
  recommendation?: RecommendationMetadata;
}
