name: Deploy Microservices to DigitalOcean

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          [
            api-gateway,
            user-service,
            auth-service,
            media-service,
            payment-service,
            mail-service,
            conversation-service,
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /var/www/microservices
            cd /var/www/microservices

            if [ ! -d ".git" ]; then
              git clone https://github.com/hieucutedangyeu/microservices-boilerplate.git .
            else
              git pull origin master
            fi

            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

            docker compose pull

            docker compose up -d --remove-orphans
